name: Deploy Infrastructure Category Service

on:
  push:
    branches:
      - main
    paths:
      - 'Infra/**' # Solo corre si hay cambios en Bicep
  workflow_dispatch: # Botón manual

permissions:
  id-token: write
  contents: read

jobs:
  deploy-bicep:
    name: Provision Web App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Bicep template
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az deployment group create \
              --resource-group "RSGRCUSAPPD01" \
              --template-file ./Infra/main.bicep
